name: liv_meal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  convert: ^3.1.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_polyline_points: ^3.0.1
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.3
  http: ^1.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
